using System;
using System.Collections.Generic;
using CurrencyConverter.Model.DTO;

namespace CurrencyConverter.Keys
{
	public static class ExchangeRateList
	{
        public static List<ExchangeRate> GetCurrencies()
        {
            return new List<ExchangeRate>()
            {
                new ExchangeRate() { FromCurrency = "USD", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "USD", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "EUR", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "GBP", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "PLN", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "CAD", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "AUD", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "NZD", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "CNY", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "KRW", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "INR", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "INR", ToCurrency = "RUB", Rate = 75.0},

                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "USD", Rate = 1.0},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "EUR", Rate = 0.85},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "GBP", Rate = 0.72},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "PLN", Rate = 3.9},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "CAD", Rate = 1.25},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "AUD", Rate = 1.3},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "NZD", Rate = 1.4},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "CNY", Rate = 6.4},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "KRW", Rate = 1130.0},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "INR", Rate = 74.0},
                new ExchangeRate { FromCurrency = "RUB", ToCurrency = "RUB", Rate = 75.0},
            };
        }
    }
}

